services:
  - type: web
    name: form-upload-sekolah
    runtime: node
    buildCommand: ""
    startCommand: "node server.js"
    plan: free
    envVars:
      - key: NODE_VERSION
        value: "20"
    rootDir: gform-upload
    autoDeploy: true
    disk:
      name: uploads-disk
      mountPath: /opt/render/project/src/gform-upload/uploads
      sizeGB: 1
